# Generated by Django 2.2.16 on 2022-11-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment'),
    ]

    operations = [
        migrations.RenameField('Post', 'pub_date', 'created'),
    ]
